name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: c8n.io
        username: ${{ secrets.C8N_USERNAME }}
        password: ${{ secrets.C8N_SECRET }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
#        build-args:
#          hdh
        push: true
        tags: c8n.io/lucatchomba/postgres:16
