name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to c8n.io Harbor Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: c8n.io
      #     username: ${{ secrets.C8N_USERNAME }}
      #     password: ${{ secrets.C8N_SECRET }}
        
      - name: Build and push Docker images (PostgreSQL 16)
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          build-args: |
            PGVERSION=16
            PGOLDVERSIONS=
            TIMESCALEDB=2.16.1
            COMPRESS=true
            PARADEDB_TELEMETRY=false
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            alvsoft/postgres:16
            alvsoft/postgres:latest

# c8n.io/lucatchomba/postgres:16
# c8n.io/lucatchomba/postgres:latest
# ghcr.io/alvsoft/postgres:latest
# ghcr.io/alvsoft/postgres:16
